CREATE TABLE STUDENTS(
    STUDENT_ID INT,
    NAME VARCHAR(100),
    AGE INT,
    COURSE_ID INT,
    PHONE_NUMBER INT);

CREATE TABLE COURSES(
COURSE_ID INT,
COURSE NAME
);

CREATE TABLE ENROLLED(
COURSE_ID INT,
STUDENT_ID INT, 
COURSE_NAME VARCHAR(100),
FACULTY_NAME VARCHAR(100)
);

